export const TEST_DISPATCH = 'TEST_DISPATCH'
export const GET_ERRORS = 'GET_ERRORS'
// Auth types
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

// Profile types
export const GET_CURRENT_PROFILE = 'GET_CURRENT_PROFILE'
export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND'
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE'